# Generated by Django 3.2.17 on 2023-02-06 15:31

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[user.validators.validate_username], verbose_name='username'),
        ),
    ]
