# Generated by Django 3.2 on 2023-01-31 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_auto_20230201_0134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'default_related_name': 'comments', 'ordering': ['-pub_date']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'default_related_name': 'reviews', 'ordering': ['-pub_date']},
        ),
    ]
